[package]
name = "btc-puzzle-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
hex = "0.4.3"
rayon = "1.10.0"
ripemd = "0.1.3"
secp256k1 = { version = "0.24.0"}
sha2 = "0.10.8"
